@php
    $phaseProgress = $project->phases->isEmpty() ? 0 : (int) round($project->phases->avg('progress'));
    $money = fn ($value, $currency = null) => \Illuminate\Support\Number::currency((float) $value, in: $currency ?? $project->currency, locale: app()->getLocale());
@endphp
<x-adminpanel::layouts.app :title="$project->name">
    <x-adminpanel::components.page-header :title="$project->name" :description="$project->code.' · '.$project->clientCompany->name">
        <x-slot:actions><div class="flex flex-wrap gap-2"><a href="{{ route('project-management.projects.index') }}" class="btn btn-text"><span class="icon-[tabler--arrow-left] size-5"></span>{{ __('admin.common.back') }}</a><a href="{{ route('project-management.projects.board', $project) }}" class="btn btn-soft btn-primary"><span class="icon-[tabler--layout-kanban] size-5"></span>{{ __('project-management.board.open') }}</a>@can('update_managed_projects')<a href="{{ route('project-management.projects.edit', $project) }}" class="btn btn-primary"><span class="icon-[tabler--edit] size-5"></span>{{ __('project-management.projects.edit') }}</a>@endcan</div></x-slot:actions>
    </x-adminpanel::components.page-header>
    <x-adminpanel::components.flash-message />

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div class="card p-5 shadow-sm"><p class="text-base-content/60 text-sm">{{ __('project-management.fields.progress') }}</p><p class="mt-2 text-2xl font-bold">{{ $phaseProgress }}%</p><progress class="progress progress-primary mt-3" value="{{ $phaseProgress }}" max="100"></progress></div>
        <div class="card p-5 shadow-sm"><p class="text-base-content/60 text-sm">{{ __('project-management.fields.duration') }}</p><p class="mt-2 font-semibold">{{ $project->started_at?->isoFormat('D MMM YYYY') ?: '—' }}</p><p class="text-base-content/60 text-xs">{{ __('project-management.fields.until') }} {{ $project->due_at?->isoFormat('D MMM YYYY') ?: '—' }}</p></div>
        <div class="card p-5 shadow-sm"><p class="text-base-content/60 text-sm">{{ __('project-management.fields.project_price') }}</p><p class="mt-2 text-xl font-bold">{{ $money($project->contract_value) }}</p><p class="text-base-content/60 text-xs">{{ __('project-management.fields.cost') }} {{ $money($project->estimated_cost) }}</p></div>
        <div class="card p-5 shadow-sm"><p class="text-base-content/60 text-sm">{{ __('project-management.fields.profit') }}</p><p @class(['mt-2 text-xl font-bold', 'text-success' => $project->profit_amount >= 0, 'text-error' => $project->profit_amount < 0])>{{ $money($project->profit_amount) }}</p><p class="text-base-content/60 text-xs">{{ number_format($project->profit_percentage, 1) }}%</p></div>
    </section>

    @if($project->description)<section class="card shadow-sm"><div class="card-body p-5"><h2 class="font-semibold">{{ __('project-management.fields.scope') }}</h2><p class="text-base-content/70 mt-2 whitespace-pre-line text-sm leading-6">{{ $project->description }}</p></div></section>@endif

    <section class="card shadow-md" id="phases">
        <div class="card-header border-base-content/10 flex items-center justify-between border-b p-5"><div><h2 class="text-lg font-semibold">{{ __('project-management.phases.title') }}</h2><p class="text-base-content/60 text-sm">{{ __('project-management.phases.description') }}</p></div></div>
        <div class="card-body space-y-5 p-5">
            @can('update_managed_projects')
                <details class="collapse border-base-content/15 border"><summary class="collapse-title font-medium"><span class="icon-[tabler--plus] me-2 inline size-5"></span>{{ __('project-management.phases.add') }}</summary><div class="collapse-content"><form method="POST" action="{{ route('project-management.projects.phases.store', $project) }}" class="grid gap-4 sm:grid-cols-2">@csrf
                    <input name="name" class="input sm:col-span-2" required placeholder="{{ __('project-management.fields.phase_name') }}">
                    <textarea name="description" class="textarea min-h-24" placeholder="{{ __('project-management.fields.phase_scope') }}"></textarea><textarea name="deliverables" class="textarea min-h-24" placeholder="{{ __('project-management.fields.deliverables') }}"></textarea>
                    <select name="status" class="select">@foreach(__('project-management.status.phases') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><input type="number" name="progress" min="0" max="100" value="0" class="input" placeholder="Progress %">
                    <input type="date" name="started_at" class="input"><input type="date" name="due_at" class="input"><input type="date" name="completed_at" class="input"><input type="number" name="sort_order" value="{{ $project->phases->count() + 1 }}" min="0" class="input">
                    <button class="btn btn-primary sm:col-span-2 sm:justify-self-end">{{ __('admin.common.save') }}</button>
                </form></div></details>
            @endcan

            @forelse($project->phases as $phase)
                <article class="border-base-content/15 overflow-hidden rounded-xl border">
                    <div class="bg-base-200/50 flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><h3 class="font-semibold">{{ $phase->sort_order }}. {{ $phase->name }}</h3><span class="badge badge-sm badge-soft">{{ __('project-management.status.phases.'.$phase->status) }}</span></div><p class="text-base-content/60 mt-1 text-xs">{{ $phase->started_at?->isoFormat('D MMM YYYY') ?: '—' }} — {{ $phase->due_at?->isoFormat('D MMM YYYY') ?: '—' }}</p></div><div class="flex min-w-44 items-center gap-3"><progress class="progress progress-primary" value="{{ $phase->progress }}" max="100"></progress><span class="text-sm font-semibold">{{ $phase->progress }}%</span></div></div>
                    <div class="space-y-4 p-4">
                        @if($phase->description || $phase->deliverables)<div class="grid gap-4 text-sm md:grid-cols-2"><div><p class="font-medium">{{ __('project-management.fields.phase_scope') }}</p><p class="text-base-content/70 mt-1 whitespace-pre-line">{{ $phase->description ?: '—' }}</p></div><div><p class="font-medium">{{ __('project-management.fields.deliverables') }}</p><p class="text-base-content/70 mt-1 whitespace-pre-line">{{ $phase->deliverables ?: '—' }}</p></div></div>@endif
                        <div>
                            <p class="mb-2 text-sm font-medium">{{ __('project-management.features.title') }}</p>
                            <div class="space-y-2">
                                @forelse($phase->features as $feature)
                                    <div class="bg-base-200/50 rounded-lg p-3">
                                        <div class="flex items-start justify-between gap-3">
                                            <div><p class="text-sm font-medium">{{ $feature->name }}</p><p class="text-base-content/60 mt-1 text-xs">{{ $feature->description }}</p><span class="badge badge-xs badge-soft mt-2">{{ __('project-management.status.features.'.$feature->status) }}</span></div>
                                            @can('update_managed_projects')
                                                <form method="POST" action="{{ route('project-management.projects.phases.features.destroy', [$project, $phase, $feature]) }}" onsubmit="return confirm(@js(__('project-management.common.delete_confirm')))">@csrf @method('DELETE')<button class="btn btn-text btn-square btn-xs text-error"><span class="icon-[tabler--trash] size-4"></span></button></form>
                                            @endcan
                                        </div>
                                        @can('update_managed_projects')
                                            <details class="mt-2"><summary class="link link-primary cursor-pointer text-xs">{{ __('project-management.features.edit') }}</summary><form method="POST" action="{{ route('project-management.projects.phases.features.update', [$project, $phase, $feature]) }}" class="mt-3 grid gap-2 sm:grid-cols-2">@csrf @method('PUT')<input name="name" value="{{ $feature->name }}" class="input input-sm sm:col-span-2" required><textarea name="description" class="textarea textarea-sm">{{ $feature->description }}</textarea><textarea name="acceptance_criteria" class="textarea textarea-sm">{{ $feature->acceptance_criteria }}</textarea><select name="status" class="select select-sm">@foreach(__('project-management.status.features') as $value => $label)<option value="{{ $value }}" @selected($feature->status === $value)>{{ $label }}</option>@endforeach</select><input type="number" name="sort_order" value="{{ $feature->sort_order }}" min="0" class="input input-sm"><button class="btn btn-primary btn-sm sm:col-span-2 sm:justify-self-end">{{ __('admin.common.save_changes') }}</button></form></details>
                                        @endcan
                                    </div>
                                @empty
                                    <p class="text-base-content/50 text-sm">{{ __('project-management.features.empty') }}</p>
                                @endforelse
                            </div>
                        </div>
                        @can('update_managed_projects')<details class="collapse border-base-content/10 border"><summary class="collapse-title py-3 text-sm font-medium">{{ __('project-management.features.add') }}</summary><div class="collapse-content"><form method="POST" action="{{ route('project-management.projects.phases.features.store', [$project, $phase]) }}" class="grid gap-3 sm:grid-cols-2">@csrf<input name="name" class="input sm:col-span-2" required placeholder="{{ __('project-management.fields.feature_name') }}"><textarea name="description" class="textarea" placeholder="{{ __('project-management.fields.description') }}"></textarea><textarea name="acceptance_criteria" class="textarea" placeholder="{{ __('project-management.fields.acceptance_criteria') }}"></textarea><select name="status" class="select">@foreach(__('project-management.status.features') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><input type="number" name="sort_order" min="0" value="{{ $phase->features->count()+1 }}" class="input"><button class="btn btn-primary sm:col-span-2 sm:justify-self-end">{{ __('admin.common.save') }}</button></form></div></details>
                        <details class="collapse border-base-content/10 border"><summary class="collapse-title py-3 text-sm font-medium">{{ __('project-management.phases.edit') }}</summary><div class="collapse-content"><form method="POST" action="{{ route('project-management.projects.phases.update', [$project, $phase]) }}" class="grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<input name="name" value="{{ $phase->name }}" class="input sm:col-span-2" required><textarea name="description" class="textarea">{{ $phase->description }}</textarea><textarea name="deliverables" class="textarea">{{ $phase->deliverables }}</textarea><select name="status" class="select">@foreach(__('project-management.status.phases') as $value => $label)<option value="{{ $value }}" @selected($phase->status===$value)>{{ $label }}</option>@endforeach</select><input type="number" name="progress" value="{{ $phase->progress }}" min="0" max="100" class="input"><input type="date" name="started_at" value="{{ $phase->started_at?->format('Y-m-d') }}" class="input"><input type="date" name="due_at" value="{{ $phase->due_at?->format('Y-m-d') }}" class="input"><input type="date" name="completed_at" value="{{ $phase->completed_at?->format('Y-m-d') }}" class="input"><input type="number" name="sort_order" value="{{ $phase->sort_order }}" class="input"><div class="flex justify-end gap-2 sm:col-span-2"><button class="btn btn-primary">{{ __('admin.common.save_changes') }}</button></div></form><form method="POST" action="{{ route('project-management.projects.phases.destroy', [$project, $phase]) }}" onsubmit="return confirm(@js(__('project-management.common.delete_confirm')))" class="mt-3 flex justify-end">@csrf @method('DELETE')<button class="btn btn-error btn-soft btn-sm">{{ __('project-management.phases.delete') }}</button></form></div></details>@endcan
                    </div>
                </article>
            @empty<p class="text-base-content/50 py-6 text-center">{{ __('project-management.phases.empty') }}</p>@endforelse
        </div>
    </section>

    <div class="grid gap-6 xl:grid-cols-2">
        <section class="card shadow-md" id="documents"><div class="card-header border-base-content/10 border-b p-5"><h2 class="text-lg font-semibold">{{ __('project-management.documents.title') }}</h2><p class="text-base-content/60 text-sm">{{ __('project-management.documents.description') }}</p></div><div class="card-body space-y-4 p-5">
            @can('update_managed_projects')<form method="POST" enctype="multipart/form-data" action="{{ route('project-management.projects.documents.store', $project) }}" class="bg-base-200/40 grid gap-3 rounded-xl p-4">@csrf<select name="category" class="select" required>@foreach(__('project-management.categories.documents') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><input type="file" name="documents[]" class="input" multiple required><textarea name="notes" class="textarea" placeholder="{{ __('project-management.fields.notes') }}"></textarea><button class="btn btn-primary justify-self-end"><span class="icon-[tabler--upload] size-5"></span>{{ __('project-management.documents.upload') }}</button></form>@endcan
            <div class="space-y-2">@forelse($project->documents as $document)<div class="border-base-content/10 flex items-center justify-between gap-3 rounded-lg border p-3"><div class="min-w-0"><p class="truncate text-sm font-medium">{{ $document->title }}</p><p class="text-base-content/60 text-xs">{{ __('project-management.categories.documents.'.$document->category) }} · {{ \Illuminate\Support\Number::fileSize($document->byte_size) }}</p></div><div class="flex gap-1"><a href="{{ route('project-management.projects.documents.download', [$project, $document]) }}" class="btn btn-soft btn-square btn-sm"><span class="icon-[tabler--download] size-4"></span></a>@can('update_managed_projects')<form method="POST" action="{{ route('project-management.projects.documents.destroy', [$project, $document]) }}" onsubmit="return confirm(@js(__('project-management.common.delete_confirm')))" >@csrf @method('DELETE')<button class="btn btn-text btn-square btn-sm text-error"><span class="icon-[tabler--trash] size-4"></span></button></form>@endcan</div></div>@empty<p class="text-base-content/50 py-5 text-center">{{ __('project-management.documents.empty') }}</p>@endforelse</div>
        </div></section>

        <section class="card shadow-md" id="technologies"><div class="card-header border-base-content/10 border-b p-5"><h2 class="text-lg font-semibold">{{ __('project-management.technologies.title') }}</h2><p class="text-base-content/60 text-sm">{{ __('project-management.technologies.description') }}</p></div><div class="card-body space-y-4 p-5">
            @can('update_managed_projects')<form method="POST" action="{{ route('project-management.projects.technologies.store', $project) }}" class="bg-base-200/40 grid gap-3 rounded-xl p-4 sm:grid-cols-2">@csrf<input name="name" class="input" required placeholder="Laravel"><input name="version" class="input" placeholder="12.x"><input name="category" class="input" placeholder="Backend / Database"><input name="notes" class="input" placeholder="{{ __('project-management.fields.notes') }}"><button class="btn btn-primary sm:col-span-2 sm:justify-self-end">{{ __('project-management.technologies.add') }}</button></form>@endcan
            <div class="flex flex-wrap gap-2">@forelse($project->technologies as $technology)<span class="badge badge-soft badge-primary gap-2 py-3">{{ $technology->name }} {{ $technology->version }} @can('update_managed_projects')<form method="POST" action="{{ route('project-management.projects.technologies.destroy', [$project, $technology]) }}">@csrf @method('DELETE')<button class="text-error" aria-label="Hapus">×</button></form>@endcan</span>@empty<p class="text-base-content/50 py-5 text-center">{{ __('project-management.technologies.empty') }}</p>@endforelse</div>
        </div></section>
    </div>

    <section class="card shadow-md" id="servers"><div class="card-header border-base-content/10 border-b p-5"><h2 class="text-lg font-semibold">{{ __('project-management.servers.title') }}</h2><p class="text-base-content/60 text-sm">{{ __('project-management.servers.description') }}</p></div><div class="card-body space-y-5 p-5">
        @can('update_managed_projects')<details class="collapse border-base-content/15 border"><summary class="collapse-title font-medium"><span class="icon-[tabler--plus] me-2 inline size-5"></span>{{ __('project-management.servers.add') }}</summary><div class="collapse-content"><x-adminpanel::components.project-management.server-form :project="$project" /></div></details>@endcan
        <div class="grid gap-4 lg:grid-cols-2">@forelse($project->servers as $server)<article class="border-base-content/15 rounded-xl border p-4"><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold">{{ $server->name }}</h3><p class="text-base-content/60 text-xs">{{ $server->provider ?: '—' }} · {{ ucfirst($server->environment) }}</p></div><span @class(['badge badge-soft','badge-error'=> $server->expires_at?->isPast(),'badge-warning'=> $server->expires_at?->isBetween(today(),today()->addDays($server->reminder_days))])>{{ __('project-management.status.servers.'.$server->status) }}</span></div><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-base-content/60 text-xs">Host</dt><dd class="mt-1 break-all">{{ $server->host ?: '—' }}</dd></div><div><dt class="text-base-content/60 text-xs">{{ __('project-management.fields.expires_at') }}</dt><dd class="mt-1">{{ $server->expires_at?->isoFormat('D MMM YYYY') ?: '—' }}</dd></div><div><dt class="text-base-content/60 text-xs">{{ __('project-management.fields.original_cost') }}</dt><dd>{{ $money($server->base_price, $server->currency) }}</dd></div><div><dt class="text-base-content/60 text-xs">{{ __('project-management.fields.sell_price') }}</dt><dd>{{ $money($server->selling_price, $server->currency) }} <span class="text-success text-xs">({{ number_format($server->profit_percentage,1) }}%)</span></dd></div></dl><div class="mt-4 flex flex-wrap gap-2">@can('show_project_credentials')<a href="{{ route('project-management.projects.servers.credentials', [$project, $server]) }}" class="btn btn-soft btn-sm"><span class="icon-[tabler--key] size-4"></span>{{ __('project-management.servers.credentials') }}</a>@endcan @can('update_managed_projects')<details class="collapse grow border-0"><summary class="btn btn-soft btn-sm">{{ __('project-management.servers.edit') }}</summary><div class="collapse-content mt-3 px-0"><x-adminpanel::components.project-management.server-form :project="$project" :server="$server" /></div></details><form method="POST" action="{{ route('project-management.projects.servers.destroy', [$project,$server]) }}" onsubmit="return confirm(@js(__('project-management.common.delete_confirm')))" >@csrf @method('DELETE')<button class="btn btn-text btn-square btn-sm text-error"><span class="icon-[tabler--trash] size-4"></span></button></form>@endcan</div></article>@empty<p class="text-base-content/50 py-6 text-center lg:col-span-2">{{ __('project-management.servers.empty') }}</p>@endforelse</div>
    </div></section>
</x-adminpanel::layouts.app>
