@props(['project' => null, 'companies'])
@php($field = fn (string $name, mixed $default = null) => old($name, data_get($project, $name, $default)))
@php($dateField = fn (string $name) => old($name, data_get($project, $name)?->format('Y-m-d')))

<div class="grid gap-5 sm:grid-cols-2">
    <div><label for="client_company_id" class="label-text font-medium">{{ __('project-management.fields.company') }} *</label><select id="client_company_id" name="client_company_id" class="select mt-2 w-full" required><option value="">{{ __('project-management.fields.select_company') }}</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((string)$field('client_company_id') === (string)$company->id)>{{ $company->name }}</option>@endforeach</select>@error('client_company_id')<p class="text-error mt-1 text-sm">{{ $message }}</p>@enderror</div>
    <div><label for="code" class="label-text font-medium">{{ __('project-management.fields.code') }} *</label><input id="code" name="code" value="{{ $field('code') }}" class="input mt-2 w-full uppercase" required placeholder="PRJ-2026-001">@error('code')<p class="text-error mt-1 text-sm">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="name" class="label-text font-medium">{{ __('project-management.fields.project_name') }} *</label><input id="name" name="name" value="{{ $field('name') }}" class="input mt-2 w-full" required>@error('name')<p class="text-error mt-1 text-sm">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="description" class="label-text font-medium">{{ __('project-management.fields.scope') }}</label><textarea id="description" name="description" class="textarea mt-2 min-h-36 w-full" placeholder="{{ __('project-management.fields.scope_hint') }}">{{ $field('description') }}</textarea></div>
    <div><label for="status" class="label-text font-medium">Status *</label><select id="status" name="status" class="select mt-2 w-full" required>@foreach(__('project-management.status.projects') as $value => $label)<option value="{{ $value }}" @selected($field('status','planning') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><label for="currency" class="label-text font-medium">{{ __('project-management.fields.currency') }}</label><select id="currency" name="currency" class="select mt-2 w-full">@foreach(['IDR','USD','SGD'] as $currency)<option @selected($field('currency','IDR') === $currency)>{{ $currency }}</option>@endforeach</select></div>
    <div><label for="started_at" class="label-text font-medium">{{ __('project-management.fields.started_at') }}</label><input id="started_at" type="date" name="started_at" value="{{ $dateField('started_at') }}" class="input mt-2 w-full"></div>
    <div><label for="due_at" class="label-text font-medium">{{ __('project-management.fields.due_at') }}</label><input id="due_at" type="date" name="due_at" value="{{ $dateField('due_at') }}" class="input mt-2 w-full"></div>
    <div><label for="completed_at" class="label-text font-medium">{{ __('project-management.fields.completed_at') }}</label><input id="completed_at" type="date" name="completed_at" value="{{ $dateField('completed_at') }}" class="input mt-2 w-full"></div>
    <div></div>
    <div><label for="estimated_cost" class="label-text font-medium">{{ __('project-management.fields.original_cost') }} *</label><input id="estimated_cost" type="number" min="0" step="0.01" name="estimated_cost" value="{{ $field('estimated_cost',0) }}" class="input mt-2 w-full" required></div>
    <div><label for="contract_value" class="label-text font-medium">{{ __('project-management.fields.project_price') }} *</label><input id="contract_value" type="number" min="0" step="0.01" name="contract_value" value="{{ $field('contract_value',0) }}" class="input mt-2 w-full" required><p class="text-base-content/50 mt-1 text-xs">{{ __('project-management.fields.margin_hint') }}</p></div>
</div>
