@props(['project', 'server' => null])
@php($prefix = $server ? 'server-'.$server->id : 'server-new')
@php($field = fn (string $name, mixed $default = null) => old($name, data_get($server, $name, $default)))
@php($dateField = fn (string $name) => old($name, data_get($server, $name)?->format('Y-m-d')))
<form method="POST" action="{{ $server ? route('project-management.projects.servers.update', [$project, $server]) : route('project-management.projects.servers.store', $project) }}" class="grid gap-3 sm:grid-cols-2">
    @csrf @if($server) @method('PUT') @endif
    <div><label for="{{ $prefix }}-name" class="label-text text-sm">{{ __('project-management.fields.server_name') }} *</label><input id="{{ $prefix }}-name" name="name" value="{{ $field('name') }}" class="input mt-1 w-full" required></div>
    <div><label for="{{ $prefix }}-provider" class="label-text text-sm">Provider</label><input id="{{ $prefix }}-provider" name="provider" value="{{ $field('provider') }}" class="input mt-1 w-full"></div>
    <div><label for="{{ $prefix }}-environment" class="label-text text-sm">Environment</label><select id="{{ $prefix }}-environment" name="environment" class="select mt-1 w-full">@foreach(['production','staging','development','other'] as $environment)<option value="{{ $environment }}" @selected($field('environment','production')===$environment)>{{ ucfirst($environment) }}</option>@endforeach</select></div>
    <div><label for="{{ $prefix }}-host" class="label-text text-sm">Host / URL / IP</label><input id="{{ $prefix }}-host" name="host" value="{{ $field('host') }}" class="input mt-1 w-full"></div>
    <div><label for="{{ $prefix }}-port" class="label-text text-sm">Port</label><input id="{{ $prefix }}-port" type="number" name="port" value="{{ $field('port') }}" min="1" max="65535" class="input mt-1 w-full"></div>
    <div></div>
    <div><label for="{{ $prefix }}-username" class="label-text text-sm">Username {{ $server ? '' : '*' }}</label><input id="{{ $prefix }}-username" name="username" autocomplete="off" class="input mt-1 w-full" {{ $server ? '' : 'required' }}>@if($server)<p class="text-base-content/50 mt-1 text-xs">{{ __('project-management.fields.secret_unchanged') }}</p>@endif</div>
    <div><label for="{{ $prefix }}-password" class="label-text text-sm">Password {{ $server ? '' : '*' }}</label><input id="{{ $prefix }}-password" type="password" name="password" autocomplete="new-password" class="input mt-1 w-full" {{ $server ? '' : 'required' }}></div>
    <div><label for="{{ $prefix }}-api_secret" class="label-text text-sm">API Key / Token</label><input id="{{ $prefix }}-api_secret" type="password" name="api_secret" autocomplete="new-password" class="input mt-1 w-full"></div>
    <div><label for="{{ $prefix }}-credentials_note" class="label-text text-sm">{{ __('project-management.fields.credential_notes') }}</label><textarea id="{{ $prefix }}-credentials_note" name="credentials_note" class="textarea mt-1 w-full"></textarea></div>
    <div><label for="{{ $prefix }}-billing_cycle" class="label-text text-sm">{{ __('project-management.fields.billing_cycle') }}</label><select id="{{ $prefix }}-billing_cycle" name="billing_cycle" class="select mt-1 w-full">@foreach(__('project-management.billing_cycles') as $value => $label)<option value="{{ $value }}" @selected($field('billing_cycle','yearly')===$value)>{{ $label }}</option>@endforeach</select></div>
    <div><label for="{{ $prefix }}-currency" class="label-text text-sm">{{ __('project-management.fields.currency') }}</label><select id="{{ $prefix }}-currency" name="currency" class="select mt-1 w-full">@foreach(['IDR','USD','SGD'] as $currency)<option @selected($field('currency','IDR')===$currency)>{{ $currency }}</option>@endforeach</select></div>
    <div><label for="{{ $prefix }}-base_price" class="label-text text-sm">{{ __('project-management.fields.original_cost') }}</label><input id="{{ $prefix }}-base_price" type="number" name="base_price" value="{{ $field('base_price',0) }}" min="0" step="0.01" class="input mt-1 w-full" required></div>
    <div><label for="{{ $prefix }}-selling_price" class="label-text text-sm">{{ __('project-management.fields.sell_price') }}</label><input id="{{ $prefix }}-selling_price" type="number" name="selling_price" value="{{ $field('selling_price',0) }}" min="0" step="0.01" class="input mt-1 w-full" required></div>
    <div><label for="{{ $prefix }}-purchased_at" class="label-text text-sm">{{ __('project-management.fields.purchased_at') }}</label><input id="{{ $prefix }}-purchased_at" type="date" name="purchased_at" value="{{ $dateField('purchased_at') }}" class="input mt-1 w-full"></div>
    <div><label for="{{ $prefix }}-expires_at" class="label-text text-sm">{{ __('project-management.fields.expires_at') }}</label><input id="{{ $prefix }}-expires_at" type="date" name="expires_at" value="{{ $dateField('expires_at') }}" class="input mt-1 w-full"></div>
    <div><label for="{{ $prefix }}-reminder_days" class="label-text text-sm">{{ __('project-management.fields.reminder_days') }}</label><input id="{{ $prefix }}-reminder_days" type="number" name="reminder_days" value="{{ $field('reminder_days',30) }}" min="1" max="365" class="input mt-1 w-full" required></div>
    <div><label for="{{ $prefix }}-status" class="label-text text-sm">Status</label><select id="{{ $prefix }}-status" name="status" class="select mt-1 w-full">@foreach(__('project-management.status.servers') as $value => $label)<option value="{{ $value }}" @selected($field('status','active')===$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="sm:col-span-2"><label for="{{ $prefix }}-notes" class="label-text text-sm">{{ __('project-management.fields.notes') }}</label><textarea id="{{ $prefix }}-notes" name="notes" class="textarea mt-1 w-full">{{ $field('notes') }}</textarea></div>
    <button class="btn btn-primary sm:col-span-2 sm:justify-self-end">{{ $server ? __('admin.common.save_changes') : __('admin.common.save') }}</button>
</form>
